development:
  adapter: postgresql
  encoding: unicode
  database: rails_div
  pool: 5
  username: ahmed
  password: 123456789

test:
  adapter: postgresql
  encoding: unicode
  database: rails_div
  pool: 5
  username: ahmed
  password: 123456789

production:
  adapter: postgresql
  encoding: unicode
  database: rails_div
  pool: 5
  username: ahmed
  password: 123456789

